name: Add to cache

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  add-to-cache:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Add to cache
        uses: actions/cache@v3
        with:
          path: test.txt
          key: foobar
