name: Clear Cache

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  clear-cache:
    runs-on: ubuntu-22.04

    steps:
      - name: Clear all caches
        uses: actions/github-script@v6
        with: |
          const {GITHUB_TOKEN} = process.env

          const octokit = new Octokit({
            auth: GITHUB_TOKEN
          })

          const result = await octokit.request('GET /repos/{owner}/{repo}/actions/caches', {
            owner: 'geo-engine',
            repo: 'cache-test'
          });

          console.log(result);
