name: Clear Cache

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  clear-cache:
    runs-on: ubuntu-22.04

    steps:
      - name: Clear all caches
        uses: actions/github-script@v6
        with:
          script: |
            const {GITHUB_TOKEN, GITHUB_REPOSITORY} = process.env

            const [owner, repo] = GITHUB_REPOSITORY.split('/')

            console.log(`Clearing all caches for ${owner}/${repo}`)

            const result = await github.request('GET /repos/{owner}/{repo}/actions/caches', {
              owner,
              repo,
            });

            for (const cache of result.data.actions_caches) {
              console.log(`Deleting cache ${cache.id}...`);

              await octokit.request('DELETE /repos/{owner}/{repo}/actions/caches/{cache_id}', {
                owner,
                repo,
                cache_id: cache.id
              })
            }
